permalink: pretty
theme: jekyll_patternbot

patternbot:
  title: "The Retro"
  description: A small ecommerce website that sells retro electronics, apparel, music, and movie items.
  font_url: "https://use.typekit.net/mxk0huy.css"
  colors:
    background: "--color-neutral-grey"
    patterns:
      brand.logos: "--color-neutral-grey"
  rationales:
    typefaces.primary: |
      BenchNine was selected because it is a simple and clean looking sans-serif typeface that acts as a compliment to the more decorative display fonts.
    typefaces.secondary: |
      Dorsa was selected for the headings of the website because it offers a thin and narrow type appearance, while also keeping true to the retro style.
    typefaces.accent: |
      Capitol was chosen as the tertriary font choice because of its retro appearance for accent elements such as buttons.
    colors.primary: |
      The primary colours are representative of the time period in which most of the items being sold in were popular.
    colors.secondary: |
      The secondary colours act as compliments to the primary colours by being lighter in colour and more muted.
  layouts:
    default: |
      This default layout will be used for every page. It includes the header and footer.
    product: |
      This layout will be used for the [roduct listing page.
  collections:
    products:
      output: true

  defaults:
    - scope:
        path: _products
      values:
        layout: product
