title: "Header"
description: |
  The header navigation is used at the top of every page of the website. This navigation includes major page links.

patterns:
  header-nav:
    title: "Header Navigation"
    description: |
      The "header navigation" is used to direct the user to the major pages within the website. This also includes product pages, and the checkout page.
    fields:
      - name: url
        type: url
        example: "/index/"
