title: "Cards"
description: |
  Cards are used throughout the website to attract the user and send them to a different part of the page.

patterns:
  product-category:
    title: "Product Category Card"
    description: |
      The "product category" card sends the user to a product list page pertaining to that particular product category. It doesn't contain a button, but it does contain dramatic typography.
    fields:
      - name: heading
        type: string
        example: "Retro Electronics"
      - name: image
        type: string
        example: "retro-radio.jpg"
      - name: url
        type: url
        example: "/products/"
  product:
    title: "Product Card"
    description: |
      The "product" card is used on the product list page. These cards include an image of the product, a decription/title underneath, and the price of the product.
    fields:
      - name: data
        type: object
        data:
          source: "site.products[0]"
          type: Product
  shop:
    title: "Shop Card"
    description: |
      The "shop" card can be used on several different pages, however, it is primarily used on the main page. This card only includes an image of the product, as well as a button to send the user to that product page.
    fields:
      - name: image
        type: string
        example: "polaroid.jpg"
      - name: button_text
        type: string
        example: "Shop Now"
      - name: button_url
        type: url
        example: "/products/"
  similar-product:
    title: "Similar Products Card"
    description: |
      The "similar products" card is mostly used on any product details page. These are located at the bottom of the page, showcasing similar products to the currently viewed product. This card includes an image of the product and a "shop" button.
    fields:
      - name: image
        type: string
        example: "camera.jpg"
      - name: button_text
        type: string
        example: "Shop"
      - name: button_url
        type: url
        example: "/products/"
