title: "Navigation"
description: |
  Navigation is used throughout the website to help the user nagivate between pages of products and different product categories.

patterns:
  page-nav:
    title: "Page Navigation"
    description: |
      The "page navigation" is used to direct the user to the different pages of products within the website.
  section-nav:
    title: "Section Navigation"
    description: |
      The "section navigation" is used to direct the user from one category of products to another.
